### PR TITLE
feat: update auro-library to 3.0.1

### LINKED ISSUE #230: Update auro library
### Is your feature request related to a problem? Please describe.

Version 3.0.1 of auro-library needs some path updates in the documentation, but is overall far easier to use moving forward and introduces some synchronization concepts the team will be using moving forward.

### Describe the solution you'd like

Update to v3.0.1 of auro-library and make sure `index.md` and `api.md` paths are updated.

NOTE: anything that points to `api.md` inside of a markdown file is really referencing `docs/api.md` and NOT `docs/partials/api.md`.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Exit criteria

_No response_

### PR DESCRIPTION
**Pull request by DukeFerdinand**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #230  
## Summary:

This updates to the latest auro-library version and ensures the documentation paths are updated in `index.md` and `api.md` to match!

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [x] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Update auro-library to version 3.0.1 and adjust documentation paths to match the new directory structure.

New Features:
- Update auro-library to version 3.0.1.

Documentation:
- Update documentation paths in index.md and api.md to reflect new directory structure.

### CODE REVIEW

**Review by chrisfalaska — DISMISSED** [review]
Tested locally 🚀

**Review by chrisfalaska — CHANGES_REQUESTED** [review]
After running `npm i`, two files are deleted:

Screenshot 2024-11-15 at 10 58 12 AM

If this is intentional, they should be removed as part of the repository commit.

**Comment by sun-mota** [comment]
> After running `npm i`, two files are deleted:
> 
> Screenshot 2024-11-15 at 10 58 12 AM
> 
> If this is intentional, they should be removed as part of the repository commit.

Those files are removed from `npm run sweep` which is intentional. 
`npm run build:docs` or `npm run build:release` will generate them back

**Review by jason-capsule42 — APPROVED** [review]

**Comment by jason-capsule42** [comment]
Approving this PR but it needs to be rebased before release.

**Review by chrisfalaska — APPROVED** [review]
Tested locally 🚀

**Pull request merged**
