### PR TITLE
refactor(styles): remove userSelect:none from disabled menu options

### LINKED ISSUE #90: Remove user-select: none; CSS rule from disabled menu options
## Describe the bug

Remove user-select: none; CSS rule from disabled menu options

Original issue opened in auro-select: https://github.com/AlaskaAirlines/auro-select/issues/43

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #90

## Summary:

Removes `user-select: none;` CSS from disabled menu items.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
What bug is this causing that requires the removal of this code?

**Comment by jason-capsule42** [comment]
> What bug is this causing that requires the removal of this code?

This was a design decision - no reason to block user-select on disabled items.

Blocking user-select was never actually part of the design.

**Comment by blackfalcon** [comment]
@leeejune can you link to the version of the auro-menu we need to be referring to for this iteration? I am unaware of this design decision to not disable text selection. 

Also, now that we bring this up... I'd argue that we should use `user-select: none` on all options in a menu. This is an opinion that is shared with shoelace https://shoelace.style/components/menu and Material UI https://mui.com/components/menus/

**Comment by jason-capsule42** [comment]
> @leeejune can you link to the version of the auro-menu we need to be referring to for this iteration? I am unaware of this design decision to not disable text selection.
> 
> Also, now that we bring this up... I'd argue that we should use `user-select: none` on all options in a menu. This is an opinion that is shared with shoelace https://shoelace.style/components/menu and Material UI https://mui.com/components/menus/

Our current design doesn't call for disabling the `user-select`. 

That said, I agree with the shoelace and Material UI, in that if it is set too `none` it should be in all cases, not just disabled. That's the point of this PR. We aren't consistent in the current implementation and since the Figma doesn't call for it to be disabled we should not implement that rule selectively without that being part of the Design.

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
